/* generated by JSetup v0.95 :  at 2 de ago de 2021 23:33:57 */
package com.robsonmrsp.netflics.entity;

import java.io.Serializable;
import java.time.LocalDateTime;

import org.springframework.data.relational.core.mapping.Column;

import lombok.Data;

@Data
public abstract class AbstractEntity implements Serializable {
  private static final long serialVersionUID = -7964355524118760783L;

  @Column("CREATE_DATETIME")
  private LocalDateTime createDatetime;

  @Column("LAST_UPDATE_DATETIME")
  private LocalDateTime lastUpdateDatetime;

  @Column("USER_CREATE")
  private String userCreate;

  @Column("USER_CHANGE")
  private String userChange;
}
