/* generated by JSetup v0.95 :  at 2 de ago de 2021 23:33:58 */
package com.robsonmrsp.netflics.entity;

import java.util.UUID;

import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Column;
import org.springframework.data.relational.core.mapping.Table;

import lombok.Builder;
import lombok.Data;

@Table("GENRE")
@Data
@Builder
public class Genre extends AbstractEntity {
  private static final long serialVersionUID = 1L;

  @Id
  @Column("ID")
  private UUID id;

  @Column("NAME")
  private String name;
}
