package com.robsonmrsp.netflics.commonlibs;

import java.util.List;
/* generated by JSetup v0.95 :  at 24 de jun de 2021 00:08:18 */
public class Pagination<T> {

	private final Long totalRecords;
	private final List<T> results;

	public Pagination(Long totalRecords, List<T> results) {
		this.totalRecords = totalRecords;
		this.results = results;
	}

	public List<T> getResults() {
		return results;
	}

	public Long getTotalRecords() {
		return totalRecords;
	}
}